### PR TITLE
My first pull request

### PR DESCRIPTION
**Pull request by toliboff**
- **Created following files:**
1. index.html
2. style.css
3. test.md
4. readme.md

**- "test.md" file added into .gitignore file**

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
## Hi @toliboff 👐, 

Wow, your project is almost done well! However, There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [ ] Please add a short description in your PR to explain changes you made inside your project you can refer to this [Link](https://microverse.zendesk.com/hc/en-us/articles/360039277914-12-2-2019-Professional-Github-repository-lesson) for more clarification on how to create a professional repo
- [ ] Refer to this [Template](https://github.com/microverseinc/readme-template) to make your README more professional

### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by toliboff** [comment]
Hi, DeliceLydia 
Thank you for your feedback. I appreciate your efforts in helping us with code reviews. 
I hope I made the required changes.

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @toliboff,

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by toliboff** [comment]
**Hello** @Dipeshtwis,
Thank you for the code review and for your feedback.

**Pull request merged**
